### ISSUE TITLE
Add section on integration with UCloud

### ISSUE THREAD

**Issue by emolinaro** [SDU-eScience/Type3-Docs#8]
Users have problems understanding how to manage Type 3 projects via UCloud.

Discuss the following points:

- Login via WAYF on UCloud
- PIs will be invited to a project, they have to accept, and then we will transfer the PI role to them.
- PIs will have to invite users to their project (and users have to accept the invitation).
- Once people are in the project, they have to connect to “DeiC Large Memory HPC (SDU)” under “Providers” on the dashboard.
- Users can upload their SSH keys under Resources.
- At the moment users cannnot see their SSH username, unless they first start a job. Users with existing SSH access can see all users in their project using `myquota -l`.

**Comment by Tobias-V** [comment]
Pushed to master.

**Comment by emolinaro** [comment]
The change must be reviewed before pushing them to master.
